[
        "GET"
        "POST"
        "PUT"
        "DELETE"
        "CONNECT"
        "OPTIONS"
        "TRACE"
        "PATCH"
        "LINK"
        "UNLINK"
        "PURGE"
        "LOCK"
        "UNLOCK"
        "PROPFIND"
        "VIEW"
 ] @keyword
